### ISSUE TITLE
please amend the credits to Jan

### ISSUE THREAD

**Issue by nanjizal** [cambiata/HxTrueType#1]
please amend the credits to Jan, you have credited someone who has just moved code to github and made minor changes?
https://code.google.com/archive/p/hxswfml/

**Comment by cambiata** [comment]
Done! Thanks!

**Comment by nanjizal** [comment]
License ?
Project Information

    License: New BSD License
    39 stars
    svn-based source control

Could try contacting him about MIT:

    http://lib.haxe.org/legacy/u/jan_flanders

**Comment by nanjizal** [comment]
may come back to delete last post later

**Comment by cambiata** [comment]
Thank you, Nanjizal!
Sent an email to Jan about this (and a copy to you). Let's see what he says.
