### ISSUE TITLE
HxTrueType name not ideal.

### ISSUE THREAD

**Issue by nanjizal** [cambiata/HxTrueType#3]
HxTrueType name is not ideal since hopefully it should eventually cover to some extent other font formats?   
Consider hxGlyph since I think hxFont is already used, and hxGlyph allow even more possible future extension.
But a name that does not tie it only to TTF seems worthwhile?

**Comment by cambiata** [comment]
Hm, I don't really get this. 

Jan's format.ttf follows the TrueType file (.ttf) format (https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=iws-chapter08), and my code renders what I get out of that. There are no "sub formats" or variations of the TrueType file format as far as I know.

Other font file formats (.otf, .wof etc) must have their own corresponding Reader/Writer/Data classes.

**Comment by nanjizal** [comment]
In the Reader there is 'readOTF' so I presume the intention was to extend it in that direction. 

I was not under the impression that they were as different as jpg and png
https://docs.microsoft.com/en-us/typography/opentype/spec/otff 

Subtypes mac and pc fonts can run on either platform easily but typically don't, it's just about injecting tables and default values when missing, and skipping missing glyphs, collections are a subtype.

It's a complex topic I do not have a definative answer I just understood them having looked at c/c++ font engines that they would be treated together, but maybe it's simpler to separate them if they really are so clearly separate.

**Comment by cambiata** [comment]
Lots of things to learn! :-) The otf format seems more complex, and more like a "superset" where ttf coded glyphs (using quadratic beziers) could be used along side with ccf (using cubic beziers). http://www.differencebetween.net/technology/difference-between-ttf-and-otf/
According to the microsoft docs, even bitmaps could be used for optimized display in small sizes!

In the end - the truetype format is clearly defined and from my point of view Jan's library covers the ttf file spec - and my lib extracts the ttf glyphs and renders them.  Otf on the other hand needs to be covered by it's own library (maybe using parts of format.ttf in cases where truetype tables are used).
